services:

    fqt.dbcm.checker:
        class: FQT\DBCoreManagerBundle\Checker\EntityManager
        arguments: [ "@service_container", "%db_manager.views%","%fqtdb_core_manager.entities%" ]

    fqt.dbcm.manager.action:
        class: FQT\DBCoreManagerBundle\Checker\ActionManager
        arguments: [ "@service_container" ]

    fqt.dbcm.exception.listener:
        class: FQT\DBCoreManagerBundle\Event\Listener\ExceptionListener
        arguments: [ "@twig", "%kernel.environment%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
